// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "My App",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "My App",
            targets: ["AppModule"],
            teamIdentifier: "9NG3C5HP77",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To use AR and guide you to class"),
                .locationWhenInUse(purposeString: "To guide you to class")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/maxxfrazer/FocusEntity", .branch("main")),
        .package(url: "https://github.com/Mist3r-R/location-based-ar.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FocusEntity", package: "focusentity"),
                .product(name: "LBAR", package: "location-based-ar")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)